<?php

namespace AppBundle\Repository;

/**
 * EigenschaftRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EigenschaftRepository extends \Doctrine\ORM\EntityRepository
{
}
