<?php

namespace AppBundle\Repository;

/**
 * ZuordnungRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZuordnungRepository extends \Doctrine\ORM\EntityRepository
{
}
